# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bb4f03786a38cfc06469c8cb7a2ecb4aa95bc4d12fdbf8f023a38c7d9e62b97ec96aaf04ec1e0ec03cc3bc34772da7075775d5eed36b6cf5c0597945345cdd8b

test:
  secret_key_base: 85d05759cb5f4e9115776dffdba1c294a8f08c87690cf6c55cd00c8133ad7f7238e1327560e050e9464948ab8fc76de52e431b5cf4943c99448d032a1d0284ca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
